### ISSUE TITLE
Does the code run on my local machine or VMs?

### ISSUE THREAD

**Issue by mdasari823** [sdx4u/probius#1]
Hi Nam,

Nice work! Does your code run on my local linux machine or should I install VMs and run inside VM? I was running on my local machine. I am getting these errors.

    ovs-vsctl: Error detected while setting up 'p3p1'.  See ovs-vswitchd log for details.
    ovs-vsctl: Error detected while setting up 'p3p2'.  See ovs-vswitchd log for details.

**Comment by sdx4u** [comment]
I'm sorry for the late response.
Once you change the interface names for your environment, it would work.
